# Site
name: 'Light.Web'
description: 'Good morning life, so beautiful and bright'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: '/jtlight'
disqus: 'demowebsite'
email: 'jitao15138964075@gmail.com'

#mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    sal:
      name:           冀涛 (Ji Tao)
      site:           https://jtnight.github.io/
      avatar:         /assets/images/avatar1.jpg
      bio:            "我是冀涛。这里是我的个人网页。"
      bio2:           "目前，我是一名在读博士生，所读专业是机械工程专业，机器人方向。更多的学术专业内容或技术服务请看我的学术网站："
      bio3:           "建设这个网站是为了记录我个人的生活，收藏个人欣赏的作品。"
      email:          jitao15138964075@gmail.com
      twitter:        https://twitter.com/wowthemesnet

    #jane:
    #  name:           Jane
    #  site:           https://www.wowthemes.net
    #  avatar:         /assets/images/avatar2.jpg
    #  bio:            "Blogger, fashionista, love to explore new ideas and write on my morning coffee!"
    #  email:          fakemail@gmail.com
    #  twitter:        https://twitter.com/wowthemesnet
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]